//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Status.
        /// </summary>
        internal static string ActiveStatus {
            get {
                return ResourceManager.GetString("ActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Additional Parking Cost.
        /// </summary>
        internal static string AddAdditionalParkingCost {
            get {
                return ResourceManager.GetString("AddAdditionalParkingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Parking Cost.
        /// </summary>
        internal static string AdditionalParkingCost {
            get {
                return ResourceManager.GetString("AdditionalParkingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addressline 1.
        /// </summary>
        internal static string Addressline1 {
            get {
                return ResourceManager.GetString("Addressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addressline 2.
        /// </summary>
        internal static string Addressline2 {
            get {
                return ResourceManager.GetString("Addressline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Status.
        /// </summary>
        internal static string AssignStatus {
            get {
                return ResourceManager.GetString("AssignStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To Other Executive Details Required.
        /// </summary>
        internal static string AssignToOtherExecutiveDetailsRequired {
            get {
                return ResourceManager.GetString("AssignToOtherExecutiveDetailsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Unit Details Required.
        /// </summary>
        internal static string AssignUnitDetailsRequired {
            get {
                return ResourceManager.GetString("AssignUnitDetailsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign User.
        /// </summary>
        internal static string AssignUser {
            get {
                return ResourceManager.GetString("AssignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Details Required.
        /// </summary>
        internal static string BankDetailsRequired {
            get {
                return ResourceManager.GetString("BankDetailsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Category.
        /// </summary>
        internal static string BlogCategory {
            get {
                return ResourceManager.GetString("BlogCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Category Code.
        /// </summary>
        internal static string BlogCategoryCode {
            get {
                return ResourceManager.GetString("BlogCategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Category List.
        /// </summary>
        internal static string BlogCategoryList {
            get {
                return ResourceManager.GetString("BlogCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Category Name.
        /// </summary>
        internal static string BlogCategoryName {
            get {
                return ResourceManager.GetString("BlogCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Code.
        /// </summary>
        internal static string BlogCode {
            get {
                return ResourceManager.GetString("BlogCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Details.
        /// </summary>
        internal static string BlogDetails {
            get {
                return ResourceManager.GetString("BlogDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Entry.
        /// </summary>
        internal static string BlogEntry {
            get {
                return ResourceManager.GetString("BlogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blogs List.
        /// </summary>
        internal static string BlogsList {
            get {
                return ResourceManager.GetString("BlogsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget List.
        /// </summary>
        internal static string BudgetList {
            get {
                return ResourceManager.GetString("BudgetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Master.
        /// </summary>
        internal static string BudgetMaster {
            get {
                return ResourceManager.GetString("BudgetMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget Name.
        /// </summary>
        internal static string BudgetName {
            get {
                return ResourceManager.GetString("BudgetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builder.
        /// </summary>
        internal static string Builder {
            get {
                return ResourceManager.GetString("Builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Builder/Person Name.
        /// </summary>
        internal static string BuilderPersonName {
            get {
                return ResourceManager.GetString("BuilderPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buildup Area.
        /// </summary>
        internal static string BuildupArea {
            get {
                return ResourceManager.GetString("BuildupArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carpet Area.
        /// </summary>
        internal static string CarpetArea {
            get {
                return ResourceManager.GetString("CarpetArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Code.
        /// </summary>
        internal static string CategoryCode {
            get {
                return ResourceManager.GetString("CategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Code.
        /// </summary>
        internal static string ColorCode {
            get {
                return ResourceManager.GetString("ColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Status.
        /// </summary>
        internal static string CompareStatus {
            get {
                return ResourceManager.GetString("CompareStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Project Details.
        /// </summary>
        internal static string CompletedProjectDetails {
            get {
                return ResourceManager.GetString("CompletedProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No 1.
        /// </summary>
        internal static string ContactNo1 {
            get {
                return ResourceManager.GetString("ContactNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact No 2.
        /// </summary>
        internal static string ContactNo2 {
            get {
                return ResourceManager.GetString("ContactNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Person Name.
        /// </summary>
        internal static string ContactPersonName {
            get {
                return ResourceManager.GetString("ContactPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Towers.
        /// </summary>
        internal static string CopyTowers {
            get {
                return ResourceManager.GetString("CopyTowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Addressline 1.
        /// </summary>
        internal static string CorporateAddressline1 {
            get {
                return ResourceManager.GetString("CorporateAddressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate Addressline 2.
        /// </summary>
        internal static string CorporateAddressline2 {
            get {
                return ResourceManager.GetString("CorporateAddressline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer&apos;s Interest Level.
        /// </summary>
        internal static string CustomersInterestLevel {
            get {
                return ResourceManager.GetString("CustomersInterestLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customers List.
        /// </summary>
        internal static string CustomersList {
            get {
                return ResourceManager.GetString("CustomersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discussion.
        /// </summary>
        internal static string Discussion {
            get {
                return ResourceManager.GetString("Discussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D Link.
        /// </summary>
        internal static string DLink {
            get {
                return ResourceManager.GetString("DLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailID.
        /// </summary>
        internal static string EmailID {
            get {
                return ResourceManager.GetString("EmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id 1.
        /// </summary>
        internal static string EmailId1 {
            get {
                return ResourceManager.GetString("EmailId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id 2.
        /// </summary>
        internal static string EmailId2 {
            get {
                return ResourceManager.GetString("EmailId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Code.
        /// </summary>
        internal static string EmployeeCode {
            get {
                return ResourceManager.GetString("EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Details.
        /// </summary>
        internal static string EmployeeDetails {
            get {
                return ResourceManager.GetString("EmployeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee First Name.
        /// </summary>
        internal static string EmployeeFirstName {
            get {
                return ResourceManager.GetString("EmployeeFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Last Name.
        /// </summary>
        internal static string EmployeeLastName {
            get {
                return ResourceManager.GetString("EmployeeLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee User List.
        /// </summary>
        internal static string EmployeeUserList {
            get {
                return ResourceManager.GetString("EmployeeUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee User Master.
        /// </summary>
        internal static string EmployeeUserMaster {
            get {
                return ResourceManager.GetString("EmployeeUserMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry Source.
        /// </summary>
        internal static string EnquirySource {
            get {
                return ResourceManager.GetString("EnquirySource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry Source List.
        /// </summary>
        internal static string EnquirySourceList {
            get {
                return ResourceManager.GetString("EnquirySourceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry Source Master.
        /// </summary>
        internal static string EnquirySourceMaster {
            get {
                return ResourceManager.GetString("EnquirySourceMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry Source Name.
        /// </summary>
        internal static string EnquirySourceName {
            get {
                return ResourceManager.GetString("EnquirySourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Link.
        /// </summary>
        internal static string EnterLink {
            get {
                return ResourceManager.GetString("EnterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Social Media Or Video Links.
        /// </summary>
        internal static string EnterSocialMediaOrVideoLinks {
            get {
                return ResourceManager.GetString("EnterSocialMediaOrVideoLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Date.
        /// </summary>
        internal static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executives.
        /// </summary>
        internal static string Executives {
            get {
                return ResourceManager.GetString("Executives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executives List.
        /// </summary>
        internal static string ExecutivesList {
            get {
                return ResourceManager.GetString("ExecutivesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Data.
        /// </summary>
        internal static string FilterData {
            get {
                return ResourceManager.GetString("FilterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter List.
        /// </summary>
        internal static string FilterList {
            get {
                return ResourceManager.GetString("FilterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First or Last Name.
        /// </summary>
        internal static string FirstorLastName {
            get {
                return ResourceManager.GetString("FirstorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Event Date.
        /// </summary>
        internal static string FromEventDate {
            get {
                return ResourceManager.GetString("FromEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST Applicable.
        /// </summary>
        internal static string GSTApplicable {
            get {
                return ResourceManager.GetString("GSTApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Level Master.
        /// </summary>
        internal static string InterestLevelMaster {
            get {
                return ResourceManager.GetString("InterestLevelMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Level Name.
        /// </summary>
        internal static string InterestLevelName {
            get {
                return ResourceManager.GetString("InterestLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch Date.
        /// </summary>
        internal static string LaunchDate {
            get {
                return ResourceManager.GetString("LaunchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        internal static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Access.
        /// </summary>
        internal static string LoginAccess {
            get {
                return ResourceManager.GetString("LoginAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Report.
        /// </summary>
        internal static string LogReport {
            get {
                return ResourceManager.GetString("LogReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Rights.
        /// </summary>
        internal static string ManageRights {
            get {
                return ResourceManager.GetString("ManageRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobileno.
        /// </summary>
        internal static string Mobileno {
            get {
                return ResourceManager.GetString("Mobileno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Of Project.
        /// </summary>
        internal static string NameOfProject {
            get {
                return ResourceManager.GetString("NameOfProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Details.
        /// </summary>
        internal static string OtherDetails {
            get {
                return ResourceManager.GetString("OtherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party List.
        /// </summary>
        internal static string PartyList {
            get {
                return ResourceManager.GetString("PartyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Master.
        /// </summary>
        internal static string PartyMaster {
            get {
                return ResourceManager.GetString("PartyMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Name.
        /// </summary>
        internal static string PartyName {
            get {
                return ResourceManager.GetString("PartyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Other Details.
        /// </summary>
        internal static string PartyOtherDetails {
            get {
                return ResourceManager.GetString("PartyOtherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Profile.
        /// </summary>
        internal static string PartyProfile {
            get {
                return ResourceManager.GetString("PartyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Type.
        /// </summary>
        internal static string PartyType {
            get {
                return ResourceManager.GetString("PartyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Type List.
        /// </summary>
        internal static string PartyTypeList {
            get {
                return ResourceManager.GetString("PartyTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Type Master.
        /// </summary>
        internal static string PartyTypeMaster {
            get {
                return ResourceManager.GetString("PartyTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Type Name.
        /// </summary>
        internal static string PartyTypeName {
            get {
                return ResourceManager.GetString("PartyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pincode.
        /// </summary>
        internal static string Pincode {
            get {
                return ResourceManager.GetString("Pincode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Assign Status.
        /// </summary>
        internal static string PleaseAssignStatus {
            get {
                return ResourceManager.GetString("PleaseAssignStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Assign User.
        /// </summary>
        internal static string PleaseAssignUser {
            get {
                return ResourceManager.GetString("PleaseAssignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter 3D link.
        /// </summary>
        internal static string PleaseEnter3Dlink {
            get {
                return ResourceManager.GetString("PleaseEnter3Dlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Addressline 1.
        /// </summary>
        internal static string PleaseEnterAddressline1 {
            get {
                return ResourceManager.GetString("PleaseEnterAddressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Addressline 2.
        /// </summary>
        internal static string PleaseEnterAddressline2 {
            get {
                return ResourceManager.GetString("PleaseEnterAddressline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Avg. Price.
        /// </summary>
        internal static string PleaseEnterAvgPrice {
            get {
                return ResourceManager.GetString("PleaseEnterAvgPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Blog Category Name.
        /// </summary>
        internal static string PleaseEnterBlogCategoryName {
            get {
                return ResourceManager.GetString("PleaseEnterBlogCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Budget.
        /// </summary>
        internal static string PleaseEnterBudget {
            get {
                return ResourceManager.GetString("PleaseEnterBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Budget Name.
        /// </summary>
        internal static string PleaseEnterBudgetName {
            get {
                return ResourceManager.GetString("PleaseEnterBudgetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Buildup Area.
        /// </summary>
        internal static string PleaseEnterBuildupArea {
            get {
                return ResourceManager.GetString("PleaseEnterBuildupArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Carpet Area.
        /// </summary>
        internal static string PleaseEnterCarpetArea {
            get {
                return ResourceManager.GetString("PleaseEnterCarpetArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Color Code.
        /// </summary>
        internal static string PleaseEnterColorCode {
            get {
                return ResourceManager.GetString("PleaseEnterColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Config.
        /// </summary>
        internal static string PleaseEnterConfig {
            get {
                return ResourceManager.GetString("PleaseEnterConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Description.
        /// </summary>
        internal static string PleaseEnterDescription {
            get {
                return ResourceManager.GetString("PleaseEnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Discussion.
        /// </summary>
        internal static string PleaseEnterDiscussion {
            get {
                return ResourceManager.GetString("PleaseEnterDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter EmailID.
        /// </summary>
        internal static string PleaseEnterEmailID {
            get {
                return ResourceManager.GetString("PleaseEnterEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Enquiry Source Name.
        /// </summary>
        internal static string PleaseEnterEnquirySourceName {
            get {
                return ResourceManager.GetString("PleaseEnterEnquirySourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter First Name.
        /// </summary>
        internal static string PleaseEnterFirstName {
            get {
                return ResourceManager.GetString("PleaseEnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter From Date.
        /// </summary>
        internal static string PleaseEnterFromDate {
            get {
                return ResourceManager.GetString("PleaseEnterFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Interest Level Name.
        /// </summary>
        internal static string PleaseEnterInterestLevelName {
            get {
                return ResourceManager.GetString("PleaseEnterInterestLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Last Name.
        /// </summary>
        internal static string PleaseEnterLastName {
            get {
                return ResourceManager.GetString("PleaseEnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Launch Date.
        /// </summary>
        internal static string PleaseEnterLaunchDate {
            get {
                return ResourceManager.GetString("PleaseEnterLaunchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Link.
        /// </summary>
        internal static string PleaseEnterLink {
            get {
                return ResourceManager.GetString("PleaseEnterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Locality.
        /// </summary>
        internal static string PleaseEnterLocality {
            get {
                return ResourceManager.GetString("PleaseEnterLocality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Name of Past Project.
        /// </summary>
        internal static string PleaseEnterNameofPastProject {
            get {
                return ResourceManager.GetString("PleaseEnterNameofPastProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Parking Cost.
        /// </summary>
        internal static string PleaseEnterParkingCost {
            get {
                return ResourceManager.GetString("PleaseEnterParkingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Party Name.
        /// </summary>
        internal static string PleaseEnterPartyName {
            get {
                return ResourceManager.GetString("PleaseEnterPartyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Party Type Name.
        /// </summary>
        internal static string PleaseEnterPartyTypeName {
            get {
                return ResourceManager.GetString("PleaseEnterPartyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Price per Sq.Ft..
        /// </summary>
        internal static string PleaseEnterPriceperSqFt {
            get {
                return ResourceManager.GetString("PleaseEnterPriceperSqFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Priority.
        /// </summary>
        internal static string PleaseEnterPriority {
            get {
                return ResourceManager.GetString("PleaseEnterPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Project Amenities.
        /// </summary>
        internal static string PleaseEnterProjectAmenities {
            get {
                return ResourceManager.GetString("PleaseEnterProjectAmenities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Project Name.
        /// </summary>
        internal static string PleaseEnterProjectName {
            get {
                return ResourceManager.GetString("PleaseEnterProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Project Prefitting.
        /// </summary>
        internal static string PleaseEnterProjectPrefitting {
            get {
                return ResourceManager.GetString("PleaseEnterProjectPrefitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter ProjectType Name.
        /// </summary>
        internal static string PleaseEnterProjectTypeName {
            get {
                return ResourceManager.GetString("PleaseEnterProjectTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Property Category Name.
        /// </summary>
        internal static string PleaseEnterPropertyCategoryName {
            get {
                return ResourceManager.GetString("PleaseEnterPropertyCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Property Config Name.
        /// </summary>
        internal static string PleaseEnterPropertyConfigName {
            get {
                return ResourceManager.GetString("PleaseEnterPropertyConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Property Facing Name.
        /// </summary>
        internal static string PleaseEnterPropertyFacingName {
            get {
                return ResourceManager.GetString("PleaseEnterPropertyFacingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Property Floor Name.
        /// </summary>
        internal static string PleaseEnterPropertyFloorName {
            get {
                return ResourceManager.GetString("PleaseEnterPropertyFloorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Property Status Name.
        /// </summary>
        internal static string PleaseEnterPropertyStatusName {
            get {
                return ResourceManager.GetString("PleaseEnterPropertyStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Property Type Name.
        /// </summary>
        internal static string PleaseEnterPropertyTypeName {
            get {
                return ResourceManager.GetString("PleaseEnterPropertyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Property Vastu.
        /// </summary>
        internal static string PleaseEnterPropertyVastu {
            get {
                return ResourceManager.GetString("PleaseEnterPropertyVastu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Purpose Name.
        /// </summary>
        internal static string PleaseEnterPurposeName {
            get {
                return ResourceManager.GetString("PleaseEnterPurposeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter RERA No.
        /// </summary>
        internal static string PleaseEnterRERANo {
            get {
                return ResourceManager.GetString("PleaseEnterRERANo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Small Description.
        /// </summary>
        internal static string PleaseEnterSmallDescription {
            get {
                return ResourceManager.GetString("PleaseEnterSmallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter State Of RERA.
        /// </summary>
        internal static string PleaseEnterStateOfRERA {
            get {
                return ResourceManager.GetString("PleaseEnterStateOfRERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Status Name.
        /// </summary>
        internal static string PleaseEnterStatusName {
            get {
                return ResourceManager.GetString("PleaseEnterStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Tags.
        /// </summary>
        internal static string PleaseEnterTags {
            get {
                return ResourceManager.GetString("PleaseEnterTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Title.
        /// </summary>
        internal static string PleaseEnterTitle {
            get {
                return ResourceManager.GetString("PleaseEnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter To Date.
        /// </summary>
        internal static string PleaseEnterToDate {
            get {
                return ResourceManager.GetString("PleaseEnterToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Tower Name.
        /// </summary>
        internal static string PleaseEnterTowerName {
            get {
                return ResourceManager.GetString("PleaseEnterTowerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Tower RERA No.
        /// </summary>
        internal static string PleaseEnterTowerRERANo {
            get {
                return ResourceManager.GetString("PleaseEnterTowerRERANo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Unit Name.
        /// </summary>
        internal static string PleaseEnterUnitName {
            get {
                return ResourceManager.GetString("PleaseEnterUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Unit Status Name.
        /// </summary>
        internal static string PleaseEnterUnitStatusName {
            get {
                return ResourceManager.GetString("PleaseEnterUnitStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Event Date.
        /// </summary>
        internal static string PleaseEnterValidEventDate {
            get {
                return ResourceManager.GetString("PleaseEnterValidEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Next Visit Date &amp; Time.
        /// </summary>
        internal static string PleaseEnterValidNextVisitDateTime {
            get {
                return ResourceManager.GetString("PleaseEnterValidNextVisitDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Valid Visit Date.
        /// </summary>
        internal static string PleaseEnterValidVisitDate {
            get {
                return ResourceManager.GetString("PleaseEnterValidVisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Builder.
        /// </summary>
        internal static string PleaseSelectBuilder {
            get {
                return ResourceManager.GetString("PleaseSelectBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Builder&apos;s Team Members.
        /// </summary>
        internal static string PleaseSelectBuildersTeamMembers {
            get {
                return ResourceManager.GetString("PleaseSelectBuildersTeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Category.
        /// </summary>
        internal static string PleaseSelectCategory {
            get {
                return ResourceManager.GetString("PleaseSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Config.
        /// </summary>
        internal static string PleaseSelectConfig {
            get {
                return ResourceManager.GetString("PleaseSelectConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Floor.
        /// </summary>
        internal static string PleaseSelectFloor {
            get {
                return ResourceManager.GetString("PleaseSelectFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Interest Level.
        /// </summary>
        internal static string PleaseSelectInterestLevel {
            get {
                return ResourceManager.GetString("PleaseSelectInterestLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Party Type.
        /// </summary>
        internal static string PleaseSelectPartyType {
            get {
                return ResourceManager.GetString("PleaseSelectPartyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Possession Month and Year.
        /// </summary>
        internal static string PleaseSelectPossessionMonthandYear {
            get {
                return ResourceManager.GetString("PleaseSelectPossessionMonthandYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Project Approved Month and Year.
        /// </summary>
        internal static string PleaseSelectProjectApprovedMonthandYear {
            get {
                return ResourceManager.GetString("PleaseSelectProjectApprovedMonthandYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Property Category.
        /// </summary>
        internal static string PleaseSelectPropertyCategory {
            get {
                return ResourceManager.GetString("PleaseSelectPropertyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Property Facing.
        /// </summary>
        internal static string PleaseSelectPropertyFacing {
            get {
                return ResourceManager.GetString("PleaseSelectPropertyFacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Property Status.
        /// </summary>
        internal static string PleaseSelectPropertyStatus {
            get {
                return ResourceManager.GetString("PleaseSelectPropertyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Property Type.
        /// </summary>
        internal static string PleaseSelectPropertyType {
            get {
                return ResourceManager.GetString("PleaseSelectPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Property vastu.
        /// </summary>
        internal static string PleaseSelectPropertyvastu {
            get {
                return ResourceManager.GetString("PleaseSelectPropertyvastu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Purpose of Meeting.
        /// </summary>
        internal static string PleaseSelectPurposeofMeeting {
            get {
                return ResourceManager.GetString("PleaseSelectPurposeofMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Site.
        /// </summary>
        internal static string PleaseSelectSite {
            get {
                return ResourceManager.GetString("PleaseSelectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select State Of RERA Registering.
        /// </summary>
        internal static string PleaseSelectStateOfRERARegistering {
            get {
                return ResourceManager.GetString("PleaseSelectStateOfRERARegistering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Status.
        /// </summary>
        internal static string PleaseSelectStatus {
            get {
                return ResourceManager.GetString("PleaseSelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Thumbnail.
        /// </summary>
        internal static string PleaseSelectThumbnail {
            get {
                return ResourceManager.GetString("PleaseSelectThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Tower.
        /// </summary>
        internal static string PleaseSelectTower {
            get {
                return ResourceManager.GetString("PleaseSelectTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Type.
        /// </summary>
        internal static string PleaseSelectType {
            get {
                return ResourceManager.GetString("PleaseSelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Year.
        /// </summary>
        internal static string PleaseSelectYear {
            get {
                return ResourceManager.GetString("PleaseSelectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possession.
        /// </summary>
        internal static string Possession {
            get {
                return ResourceManager.GetString("Possession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Per Sq.Ft..
        /// </summary>
        internal static string PricePerSqFt {
            get {
                return ResourceManager.GetString("PricePerSqFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Amenities.
        /// </summary>
        internal static string ProjectAmenities {
            get {
                return ResourceManager.GetString("ProjectAmenities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Approved On.
        /// </summary>
        internal static string ProjectApprovedOn {
            get {
                return ResourceManager.GetString("ProjectApprovedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Code.
        /// </summary>
        internal static string ProjectCode {
            get {
                return ResourceManager.GetString("ProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project List.
        /// </summary>
        internal static string ProjectList {
            get {
                return ResourceManager.GetString("ProjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Master.
        /// </summary>
        internal static string ProjectMaster {
            get {
                return ResourceManager.GetString("ProjectMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name / Party Name.
        /// </summary>
        internal static string ProjectNamePartyName {
            get {
                return ResourceManager.GetString("ProjectNamePartyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Prefitting.
        /// </summary>
        internal static string ProjectPrefitting {
            get {
                return ResourceManager.GetString("ProjectPrefitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectType.
        /// </summary>
        internal static string ProjectType {
            get {
                return ResourceManager.GetString("ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Type List.
        /// </summary>
        internal static string ProjectTypeList {
            get {
                return ResourceManager.GetString("ProjectTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectType Master.
        /// </summary>
        internal static string ProjectTypeMaster {
            get {
                return ResourceManager.GetString("ProjectTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectType Name.
        /// </summary>
        internal static string ProjectTypeName {
            get {
                return ResourceManager.GetString("ProjectTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Category.
        /// </summary>
        internal static string PropertyCategory {
            get {
                return ResourceManager.GetString("PropertyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Category List.
        /// </summary>
        internal static string PropertyCategoryList {
            get {
                return ResourceManager.GetString("PropertyCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Category Master.
        /// </summary>
        internal static string PropertyCategoryMaster {
            get {
                return ResourceManager.GetString("PropertyCategoryMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Category Name.
        /// </summary>
        internal static string PropertyCategoryName {
            get {
                return ResourceManager.GetString("PropertyCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Code.
        /// </summary>
        internal static string PropertyCode {
            get {
                return ResourceManager.GetString("PropertyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Config.
        /// </summary>
        internal static string PropertyConfig {
            get {
                return ResourceManager.GetString("PropertyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Config List.
        /// </summary>
        internal static string PropertyConfigList {
            get {
                return ResourceManager.GetString("PropertyConfigList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Config Master.
        /// </summary>
        internal static string PropertyConfigMaster {
            get {
                return ResourceManager.GetString("PropertyConfigMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Config Name.
        /// </summary>
        internal static string PropertyConfigName {
            get {
                return ResourceManager.GetString("PropertyConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Entry.
        /// </summary>
        internal static string PropertyEntry {
            get {
                return ResourceManager.GetString("PropertyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Facing.
        /// </summary>
        internal static string PropertyFacing {
            get {
                return ResourceManager.GetString("PropertyFacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Facing List.
        /// </summary>
        internal static string PropertyFacingList {
            get {
                return ResourceManager.GetString("PropertyFacingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Facing Master.
        /// </summary>
        internal static string PropertyFacingMaster {
            get {
                return ResourceManager.GetString("PropertyFacingMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Facing Name.
        /// </summary>
        internal static string PropertyFacingName {
            get {
                return ResourceManager.GetString("PropertyFacingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Floor.
        /// </summary>
        internal static string PropertyFloor {
            get {
                return ResourceManager.GetString("PropertyFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Floor List.
        /// </summary>
        internal static string PropertyFloorList {
            get {
                return ResourceManager.GetString("PropertyFloorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Floor Master.
        /// </summary>
        internal static string PropertyFloorMaster {
            get {
                return ResourceManager.GetString("PropertyFloorMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Floor Name.
        /// </summary>
        internal static string PropertyFloorName {
            get {
                return ResourceManager.GetString("PropertyFloorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Interest.
        /// </summary>
        internal static string PropertyInterest {
            get {
                return ResourceManager.GetString("PropertyInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Interest List.
        /// </summary>
        internal static string PropertyInterestList {
            get {
                return ResourceManager.GetString("PropertyInterestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property List.
        /// </summary>
        internal static string PropertyList {
            get {
                return ResourceManager.GetString("PropertyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Overview.
        /// </summary>
        internal static string PropertyOverview {
            get {
                return ResourceManager.GetString("PropertyOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Party.
        /// </summary>
        internal static string PropertyParty {
            get {
                return ResourceManager.GetString("PropertyParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Status.
        /// </summary>
        internal static string PropertyStatus {
            get {
                return ResourceManager.GetString("PropertyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Status List.
        /// </summary>
        internal static string PropertyStatusList {
            get {
                return ResourceManager.GetString("PropertyStatusList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Status Master.
        /// </summary>
        internal static string PropertyStatusMaster {
            get {
                return ResourceManager.GetString("PropertyStatusMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Status Name.
        /// </summary>
        internal static string PropertyStatusName {
            get {
                return ResourceManager.GetString("PropertyStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type.
        /// </summary>
        internal static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type List.
        /// </summary>
        internal static string PropertyTypeList {
            get {
                return ResourceManager.GetString("PropertyTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type Master.
        /// </summary>
        internal static string PropertyTypeMaster {
            get {
                return ResourceManager.GetString("PropertyTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Type Name.
        /// </summary>
        internal static string PropertyTypeName {
            get {
                return ResourceManager.GetString("PropertyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Vastu.
        /// </summary>
        internal static string PropertyVastu {
            get {
                return ResourceManager.GetString("PropertyVastu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Vastu List.
        /// </summary>
        internal static string PropertyVastuList {
            get {
                return ResourceManager.GetString("PropertyVastuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property Vastu Master.
        /// </summary>
        internal static string PropertyVastuMaster {
            get {
                return ResourceManager.GetString("PropertyVastuMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        internal static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose List.
        /// </summary>
        internal static string PurposeList {
            get {
                return ResourceManager.GetString("PurposeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose Master.
        /// </summary>
        internal static string PurposeMaster {
            get {
                return ResourceManager.GetString("PurposeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose Name.
        /// </summary>
        internal static string PurposeName {
            get {
                return ResourceManager.GetString("PurposeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose of Meeting.
        /// </summary>
        internal static string PurposeofMeeting {
            get {
                return ResourceManager.GetString("PurposeofMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Required.
        /// </summary>
        internal static string ReasonRequired {
            get {
                return ResourceManager.GetString("ReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Since.
        /// </summary>
        internal static string RegisteredSince {
            get {
                return ResourceManager.GetString("RegisteredSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RERA Applicable.
        /// </summary>
        internal static string RERAApplicable {
            get {
                return ResourceManager.GetString("RERAApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RERA No.
        /// </summary>
        internal static string RERANo {
            get {
                return ResourceManager.GetString("RERANo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RERA No compulsory.
        /// </summary>
        internal static string RERANocompulsory {
            get {
                return ResourceManager.GetString("RERANocompulsory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Visit.
        /// </summary>
        internal static string ScheduledVisit {
            get {
                return ResourceManager.GetString("ScheduledVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Next Visit.
        /// </summary>
        internal static string ScheduleNextVisit {
            get {
                return ResourceManager.GetString("ScheduleNextVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Next Visit Date.
        /// </summary>
        internal static string ScheduleNextVisitDate {
            get {
                return ResourceManager.GetString("ScheduleNextVisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Builder.
        /// </summary>
        internal static string SelectBuilder {
            get {
                return ResourceManager.GetString("SelectBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Builder&apos;s Team Members.
        /// </summary>
        internal static string SelectBuildersTeamMembers {
            get {
                return ResourceManager.GetString("SelectBuildersTeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Config.
        /// </summary>
        internal static string SelectConfig {
            get {
                return ResourceManager.GetString("SelectConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Export Format.
        /// </summary>
        internal static string SelectExportFormat {
            get {
                return ResourceManager.GetString("SelectExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Floor.
        /// </summary>
        internal static string SelectFloor {
            get {
                return ResourceManager.GetString("SelectFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Multiple Blog Images and Files.
        /// </summary>
        internal static string SelectMultipleBlogImagesandFiles {
            get {
                return ResourceManager.GetString("SelectMultipleBlogImagesandFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Multiple Property Photos and Brochure.
        /// </summary>
        internal static string SelectMultiplePropertyPhotosandBrochure {
            get {
                return ResourceManager.GetString("SelectMultiplePropertyPhotosandBrochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Project.
        /// </summary>
        internal static string SelectProject {
            get {
                return ResourceManager.GetString("SelectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Status.
        /// </summary>
        internal static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Thumbnail Image.
        /// </summary>
        internal static string SelectThumbnailImage {
            get {
                return ResourceManager.GetString("SelectThumbnailImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Tower.
        /// </summary>
        internal static string SelectTower {
            get {
                return ResourceManager.GetString("SelectTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select User.
        /// </summary>
        internal static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Login Email.
        /// </summary>
        internal static string SendLoginEmail {
            get {
                return ResourceManager.GetString("SendLoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Addressline 1.
        /// </summary>
        internal static string SiteAddressline1 {
            get {
                return ResourceManager.GetString("SiteAddressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Addressline 2.
        /// </summary>
        internal static string SiteAddressline2 {
            get {
                return ResourceManager.GetString("SiteAddressline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Name.
        /// </summary>
        internal static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small Description.
        /// </summary>
        internal static string SmallDescription {
            get {
                return ResourceManager.GetString("SmallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Media.
        /// </summary>
        internal static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Of RERA.
        /// </summary>
        internal static string StateOfRERA {
            get {
                return ResourceManager.GetString("StateOfRERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Of RERA List.
        /// </summary>
        internal static string StateOfRERAList {
            get {
                return ResourceManager.GetString("StateOfRERAList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Of RERA Master.
        /// </summary>
        internal static string StateOfRERAMaster {
            get {
                return ResourceManager.GetString("StateOfRERAMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Of RERA Registering.
        /// </summary>
        internal static string StateOfRERARegistering {
            get {
                return ResourceManager.GetString("StateOfRERARegistering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status List.
        /// </summary>
        internal static string StatusList {
            get {
                return ResourceManager.GetString("StatusList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Master.
        /// </summary>
        internal static string StatusMaster {
            get {
                return ResourceManager.GetString("StatusMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Name.
        /// </summary>
        internal static string StatusName {
            get {
                return ResourceManager.GetString("StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Event Date.
        /// </summary>
        internal static string ToEventDate {
            get {
                return ResourceManager.GetString("ToEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tower Details.
        /// </summary>
        internal static string TowerDetails {
            get {
                return ResourceManager.GetString("TowerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tower List.
        /// </summary>
        internal static string TowerList {
            get {
                return ResourceManager.GetString("TowerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Details.
        /// </summary>
        internal static string UnitDetails {
            get {
                return ResourceManager.GetString("UnitDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        internal static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Status.
        /// </summary>
        internal static string UnitStatus {
            get {
                return ResourceManager.GetString("UnitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Status List.
        /// </summary>
        internal static string UnitStatusList {
            get {
                return ResourceManager.GetString("UnitStatusList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Status Master.
        /// </summary>
        internal static string UnitStatusMaster {
            get {
                return ResourceManager.GetString("UnitStatusMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Status Name.
        /// </summary>
        internal static string UnitStatusName {
            get {
                return ResourceManager.GetString("UnitStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Own Profile Rights.
        /// </summary>
        internal static string UpdateOwnProfileRights {
            get {
                return ResourceManager.GetString("UpdateOwnProfileRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Photos.
        /// </summary>
        internal static string UploadPhotos {
            get {
                return ResourceManager.GetString("UploadPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vastu.
        /// </summary>
        internal static string Vastu {
            get {
                return ResourceManager.GetString("Vastu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility Status.
        /// </summary>
        internal static string VisibilityStatus {
            get {
                return ResourceManager.GetString("VisibilityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry Date.
        /// </summary>
        internal static string VisitDate {
            get {
                return ResourceManager.GetString("VisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit Entry.
        /// </summary>
        internal static string VisitEntry {
            get {
                return ResourceManager.GetString("VisitEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit History.
        /// </summary>
        internal static string VisitHistory {
            get {
                return ResourceManager.GetString("VisitHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit List.
        /// </summary>
        internal static string VisitList {
            get {
                return ResourceManager.GetString("VisitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit No.
        /// </summary>
        internal static string VisitNo {
            get {
                return ResourceManager.GetString("VisitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Link.
        /// </summary>
        internal static string WebsiteLink {
            get {
                return ResourceManager.GetString("WebsiteLink", resourceCulture);
            }
        }
    }
}
