//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource2 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource2() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource2", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सक्रिय स्थिती.
        /// </summary>
        internal static string ActiveStatus {
            get {
                return ResourceManager.GetString("ActiveStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अतिरिक्त पार्किंग खर्च जोडा.
        /// </summary>
        internal static string AddAdditionalParkingCost {
            get {
                return ResourceManager.GetString("AddAdditionalParkingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अतिरिक्त पार्किंग खर्च.
        /// </summary>
        internal static string AdditionalParkingCost {
            get {
                return ResourceManager.GetString("AdditionalParkingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पत्ता क्रमांक 1.
        /// </summary>
        internal static string Addressline1 {
            get {
                return ResourceManager.GetString("Addressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पत्ता ओळ 2.
        /// </summary>
        internal static string Addressline2 {
            get {
                return ResourceManager.GetString("Addressline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to क्षेत्रफळ.
        /// </summary>
        internal static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वापरकर्त्यास असाइन करा.
        /// </summary>
        internal static string AssignUser {
            get {
                return ResourceManager.GetString("AssignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ब्लॉग श्रेणी.
        /// </summary>
        internal static string BlogCategory {
            get {
                return ResourceManager.GetString("BlogCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ब्लॉग श्रेणी कोड.
        /// </summary>
        internal static string BlogCategoryCode {
            get {
                return ResourceManager.GetString("BlogCategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ब्लॉग श्रेणी यादी.
        /// </summary>
        internal static string BlogCategoryList {
            get {
                return ResourceManager.GetString("BlogCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ब्लॉग श्रेणी नाव.
        /// </summary>
        internal static string BlogCategoryName {
            get {
                return ResourceManager.GetString("BlogCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ब्लॉग कोड.
        /// </summary>
        internal static string BlogCode {
            get {
                return ResourceManager.GetString("BlogCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ब्लॉग तपशील.
        /// </summary>
        internal static string BlogDetails {
            get {
                return ResourceManager.GetString("BlogDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ब्लॉग एंट्री.
        /// </summary>
        internal static string BlogEntry {
            get {
                return ResourceManager.GetString("BlogEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ब्लॉग सूची.
        /// </summary>
        internal static string BlogsList {
            get {
                return ResourceManager.GetString("BlogsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अर्थसंकल्प.
        /// </summary>
        internal static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बजेट यादी.
        /// </summary>
        internal static string BudgetList {
            get {
                return ResourceManager.GetString("BudgetList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बजेट मास्टर.
        /// </summary>
        internal static string BudgetMaster {
            get {
                return ResourceManager.GetString("BudgetMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बजेट नाव.
        /// </summary>
        internal static string BudgetName {
            get {
                return ResourceManager.GetString("BudgetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बिल्डर.
        /// </summary>
        internal static string Builder {
            get {
                return ResourceManager.GetString("Builder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बिल्डर / व्यक्तीचे नाव.
        /// </summary>
        internal static string BuilderPersonName {
            get {
                return ResourceManager.GetString("BuilderPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बिल्डअप क्षेत्र.
        /// </summary>
        internal static string BuildupArea {
            get {
                return ResourceManager.GetString("BuildupArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चटई क्षेत्र.
        /// </summary>
        internal static string CarpetArea {
            get {
                return ResourceManager.GetString("CarpetArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to श्रेणी कोड.
        /// </summary>
        internal static string CategoryCode {
            get {
                return ResourceManager.GetString("CategoryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to श्रेणी नाव.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शहर.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कोड.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रंग कोड.
        /// </summary>
        internal static string ColorCode {
            get {
                return ResourceManager.GetString("ColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थितीची तुलना करा.
        /// </summary>
        internal static string CompareStatus {
            get {
                return ResourceManager.GetString("CompareStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पूर्ण प्रकल्प तपशील.
        /// </summary>
        internal static string CompletedProjectDetails {
            get {
                return ResourceManager.GetString("CompletedProjectDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कॉन्फिगर करा.
        /// </summary>
        internal static string Config {
            get {
                return ResourceManager.GetString("Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पुष्टीकरण.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संपर्क क्रमांक १.
        /// </summary>
        internal static string ContactNo1 {
            get {
                return ResourceManager.GetString("ContactNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संपर्क क्रमांक 2.
        /// </summary>
        internal static string ContactNo2 {
            get {
                return ResourceManager.GetString("ContactNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to संपर्क व्यक्तीचे नाव.
        /// </summary>
        internal static string ContactPersonName {
            get {
                return ResourceManager.GetString("ContactPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टॉवर्स कॉपी करा.
        /// </summary>
        internal static string CopyTowers {
            get {
                return ResourceManager.GetString("CopyTowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कॉर्पोरेट अ‍ॅड्रेसलाईन १.
        /// </summary>
        internal static string CorporateAddressline1 {
            get {
                return ResourceManager.GetString("CorporateAddressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कॉर्पोरेट अ‍ॅड्रेसलाईन २.
        /// </summary>
        internal static string CorporateAddressline2 {
            get {
                return ResourceManager.GetString("CorporateAddressline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ग्राहकाचे नाव.
        /// </summary>
        internal static string CustomerName {
            get {
                return ResourceManager.GetString("CustomerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ग्राहकांचे व्याज पातळी.
        /// </summary>
        internal static string CustomersInterestLevel {
            get {
                return ResourceManager.GetString("CustomersInterestLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ग्राहकांची यादी.
        /// </summary>
        internal static string CustomersList {
            get {
                return ResourceManager.GetString("CustomersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वर्णन.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to चर्चा.
        /// </summary>
        internal static string Discussion {
            get {
                return ResourceManager.GetString("Discussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 डी दुवा.
        /// </summary>
        internal static string DLink {
            get {
                return ResourceManager.GetString("DLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ई - मेल आयडी.
        /// </summary>
        internal static string EmailID {
            get {
                return ResourceManager.GetString("EmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ईमेल आयडी 1.
        /// </summary>
        internal static string EmailId1 {
            get {
                return ResourceManager.GetString("EmailId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ईमेल आयडी 2.
        /// </summary>
        internal static string EmailId2 {
            get {
                return ResourceManager.GetString("EmailId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कर्मचारी कोड.
        /// </summary>
        internal static string EmployeeCode {
            get {
                return ResourceManager.GetString("EmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कर्मचार्‍यांचा तपशील.
        /// </summary>
        internal static string EmployeeDetails {
            get {
                return ResourceManager.GetString("EmployeeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कर्मचारी नाव.
        /// </summary>
        internal static string EmployeeFirstName {
            get {
                return ResourceManager.GetString("EmployeeFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कर्मचारी आडनाव.
        /// </summary>
        internal static string EmployeeLastName {
            get {
                return ResourceManager.GetString("EmployeeLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कर्मचारी वापरकर्त्याची यादी.
        /// </summary>
        internal static string EmployeeUserList {
            get {
                return ResourceManager.GetString("EmployeeUserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कर्मचारी वापरकर्ता मास्टर.
        /// </summary>
        internal static string EmployeeUserMaster {
            get {
                return ResourceManager.GetString("EmployeeUserMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दुवा प्रविष्ट करा.
        /// </summary>
        internal static string EnterLink {
            get {
                return ResourceManager.GetString("EnterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सोशल मीडिया किंवा व्हिडिओ दुवे प्रविष्ट करा.
        /// </summary>
        internal static string EnterSocialMediaOrVideoLinks {
            get {
                return ResourceManager.GetString("EnterSocialMediaOrVideoLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कार्यक्रमाची तारीख.
        /// </summary>
        internal static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कार्यकारी.
        /// </summary>
        internal static string Executives {
            get {
                return ResourceManager.GetString("Executives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कार्यकारी यादी.
        /// </summary>
        internal static string ExecutivesList {
            get {
                return ResourceManager.GetString("ExecutivesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to निर्यात करा.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to फिल्टर डेटा.
        /// </summary>
        internal static string FilterData {
            get {
                return ResourceManager.GetString("FilterData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to फिल्टर यादी.
        /// </summary>
        internal static string FilterList {
            get {
                return ResourceManager.GetString("FilterList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नाव किंवा आडनाव.
        /// </summary>
        internal static string FirstorLastName {
            get {
                return ResourceManager.GetString("FirstorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to या तारखेपासून.
        /// </summary>
        internal static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कार्यक्रमाच्या तारखेपासून.
        /// </summary>
        internal static string FromEventDate {
            get {
                return ResourceManager.GetString("FromEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लिंग.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जीएसटी लागू.
        /// </summary>
        internal static string GSTApplicable {
            get {
                return ResourceManager.GetString("GSTApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to व्याज पातळी मास्टर.
        /// </summary>
        internal static string InterestLevelMaster {
            get {
                return ResourceManager.GetString("InterestLevelMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to व्याज स्तराचे नाव.
        /// </summary>
        internal static string InterestLevelName {
            get {
                return ResourceManager.GetString("InterestLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लाँच तारीख.
        /// </summary>
        internal static string LaunchDate {
            get {
                return ResourceManager.GetString("LaunchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to परिसर.
        /// </summary>
        internal static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थान.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉगिन प्रवेश.
        /// </summary>
        internal static string LoginAccess {
            get {
                return ResourceManager.GetString("LoginAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉग अहवाल.
        /// </summary>
        internal static string LogReport {
            get {
                return ResourceManager.GetString("LogReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अधिकार व्यवस्थापित करा.
        /// </summary>
        internal static string ManageRights {
            get {
                return ResourceManager.GetString("ManageRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मोबाईलनो.
        /// </summary>
        internal static string Mobileno {
            get {
                return ResourceManager.GetString("Mobileno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्पाचे नाव.
        /// </summary>
        internal static string NameOfProject {
            get {
                return ResourceManager.GetString("NameOfProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to इतर तपशील.
        /// </summary>
        internal static string OtherDetails {
            get {
                return ResourceManager.GetString("OtherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पार्टी यादी.
        /// </summary>
        internal static string PartyList {
            get {
                return ResourceManager.GetString("PartyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पार्टी मास्टर.
        /// </summary>
        internal static string PartyMaster {
            get {
                return ResourceManager.GetString("PartyMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पक्षाचे नाव.
        /// </summary>
        internal static string PartyName {
            get {
                return ResourceManager.GetString("PartyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पार्टी इतर तपशील.
        /// </summary>
        internal static string PartyOtherDetails {
            get {
                return ResourceManager.GetString("PartyOtherDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पार्टी प्रोफाइल.
        /// </summary>
        internal static string PartyProfile {
            get {
                return ResourceManager.GetString("PartyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पार्टी प्रकार.
        /// </summary>
        internal static string PartyType {
            get {
                return ResourceManager.GetString("PartyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पार्टी प्रकार यादी.
        /// </summary>
        internal static string PartyTypeList {
            get {
                return ResourceManager.GetString("PartyTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पार्टी प्रकार मास्टर.
        /// </summary>
        internal static string PartyTypeMaster {
            get {
                return ResourceManager.GetString("PartyTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पार्टी प्रकार नाव.
        /// </summary>
        internal static string PartyTypeName {
            get {
                return ResourceManager.GetString("PartyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पिन कोड.
        /// </summary>
        internal static string Pincode {
            get {
                return ResourceManager.GetString("Pincode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया वापरकर्त्यास असाइन करा.
        /// </summary>
        internal static string PleaseAssignUser {
            get {
                return ResourceManager.GetString("PleaseAssignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया 3 डी दुवा प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnter3Dlink {
            get {
                return ResourceManager.GetString("PleaseEnter3Dlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया अ‍ॅड्रेसलाइन 1 प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterAddressline1 {
            get {
                return ResourceManager.GetString("PleaseEnterAddressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया अ‍ॅड्रेसलाइन 2 प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterAddressline2 {
            get {
                return ResourceManager.GetString("PleaseEnterAddressline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया सरासरी प्रविष्ट करा. किंमत.
        /// </summary>
        internal static string PleaseEnterAvgPrice {
            get {
                return ResourceManager.GetString("PleaseEnterAvgPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया ब्लॉग श्रेणी नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterBlogCategoryName {
            get {
                return ResourceManager.GetString("PleaseEnterBlogCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया बजेट प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterBudget {
            get {
                return ResourceManager.GetString("PleaseEnterBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया बजेटचे नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterBudgetName {
            get {
                return ResourceManager.GetString("PleaseEnterBudgetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया बिल्डअप क्षेत्र प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterBuildupArea {
            get {
                return ResourceManager.GetString("PleaseEnterBuildupArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया कार्पेट क्षेत्र प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterCarpetArea {
            get {
                return ResourceManager.GetString("PleaseEnterCarpetArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया रंग कोड प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterColorCode {
            get {
                return ResourceManager.GetString("PleaseEnterColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया कॉन्फिगरेशन प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterConfig {
            get {
                return ResourceManager.GetString("PleaseEnterConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया वर्णन प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterDescription {
            get {
                return ResourceManager.GetString("PleaseEnterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया चर्चा प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterDiscussion {
            get {
                return ResourceManager.GetString("PleaseEnterDiscussion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया ईमेलआयडी प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterEmailID {
            get {
                return ResourceManager.GetString("PleaseEnterEmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया प्रथम नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterFirstName {
            get {
                return ResourceManager.GetString("PleaseEnterFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया तारखेपासून प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterFromDate {
            get {
                return ResourceManager.GetString("PleaseEnterFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया स्वारस्य पातळीचे नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterInterestLevelName {
            get {
                return ResourceManager.GetString("PleaseEnterInterestLevelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया आडनाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterLastName {
            get {
                return ResourceManager.GetString("PleaseEnterLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया प्रक्षेपण तारीख प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterLaunchDate {
            get {
                return ResourceManager.GetString("PleaseEnterLaunchDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया दुवा प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterLink {
            get {
                return ResourceManager.GetString("PleaseEnterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया परिसर प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterLocality {
            get {
                return ResourceManager.GetString("PleaseEnterLocality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया मागील प्रकल्पाचे नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterNameofPastProject {
            get {
                return ResourceManager.GetString("PleaseEnterNameofPastProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया पार्किंग खर्च प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterParkingCost {
            get {
                return ResourceManager.GetString("PleaseEnterParkingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया पक्षाचे नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterPartyName {
            get {
                return ResourceManager.GetString("PleaseEnterPartyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया पार्टी प्रकार नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterPartyTypeName {
            get {
                return ResourceManager.GetString("PleaseEnterPartyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया प्रत्येक चौरस फुट किंमत द्या..
        /// </summary>
        internal static string PleaseEnterPriceperSqFt {
            get {
                return ResourceManager.GetString("PleaseEnterPriceperSqFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया प्राधान्य प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterPriority {
            get {
                return ResourceManager.GetString("PleaseEnterPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया प्रकल्प सुविधा प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterProjectAmenities {
            get {
                return ResourceManager.GetString("PleaseEnterProjectAmenities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया प्रोजेक्ट नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterProjectName {
            get {
                return ResourceManager.GetString("PleaseEnterProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया प्रोजेक्ट प्रीफिटिंग प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterProjectPrefitting {
            get {
                return ResourceManager.GetString("PleaseEnterProjectPrefitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया प्रोजेक्टटाइप नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterProjectTypeName {
            get {
                return ResourceManager.GetString("PleaseEnterProjectTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया मालमत्ता श्रेणी नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterPropertyCategoryName {
            get {
                return ResourceManager.GetString("PleaseEnterPropertyCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया मालमत्ता कॉन्फिगरेशन नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterPropertyConfigName {
            get {
                return ResourceManager.GetString("PleaseEnterPropertyConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया मालमत्तेचे नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterPropertyFacingName {
            get {
                return ResourceManager.GetString("PleaseEnterPropertyFacingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया प्रॉपर्टी फ्लोरचे नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterPropertyFloorName {
            get {
                return ResourceManager.GetString("PleaseEnterPropertyFloorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया मालमत्ता स्थिती नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterPropertyStatusName {
            get {
                return ResourceManager.GetString("PleaseEnterPropertyStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रॉपर्टी प्रकार नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterPropertyTypeName {
            get {
                return ResourceManager.GetString("PleaseEnterPropertyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया प्रॉपर्टी वास्तु प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterPropertyVastu {
            get {
                return ResourceManager.GetString("PleaseEnterPropertyVastu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया हेतू नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterPurposeName {
            get {
                return ResourceManager.GetString("PleaseEnterPurposeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया रेरा क्रमांक प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterRERANo {
            get {
                return ResourceManager.GetString("PleaseEnterRERANo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया लहान वर्णन प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterSmallDescription {
            get {
                return ResourceManager.GetString("PleaseEnterSmallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया रेरा राज्य प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterStateOfRERA {
            get {
                return ResourceManager.GetString("PleaseEnterStateOfRERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया स्थिती नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterStatusName {
            get {
                return ResourceManager.GetString("PleaseEnterStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया टॅग प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterTags {
            get {
                return ResourceManager.GetString("PleaseEnterTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया शीर्षक प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterTitle {
            get {
                return ResourceManager.GetString("PleaseEnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया तारीख प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterToDate {
            get {
                return ResourceManager.GetString("PleaseEnterToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया टॉवरचे नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterTowerName {
            get {
                return ResourceManager.GetString("PleaseEnterTowerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया टॉवर रेरा क्रमांक प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterTowerRERANo {
            get {
                return ResourceManager.GetString("PleaseEnterTowerRERANo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया युनिट नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterUnitName {
            get {
                return ResourceManager.GetString("PleaseEnterUnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया युनिट स्थिती नाव प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterUnitStatusName {
            get {
                return ResourceManager.GetString("PleaseEnterUnitStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया वैध कार्यक्रमाची तारीख प्रविष्ट करा.
        /// </summary>
        internal static string PleaseEnterValidEventDate {
            get {
                return ResourceManager.GetString("PleaseEnterValidEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया वैध प्रविष्ट करा पुढील भेटीची तारीख आणि वेळ.
        /// </summary>
        internal static string PleaseEnterValidNextVisitDateTime {
            get {
                return ResourceManager.GetString("PleaseEnterValidNextVisitDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया बिल्डर निवडा.
        /// </summary>
        internal static string PleaseSelectBuilder {
            get {
                return ResourceManager.GetString("PleaseSelectBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया बिल्डरचे कार्यसंघ सदस्य निवडा.
        /// </summary>
        internal static string PleaseSelectBuildersTeamMembers {
            get {
                return ResourceManager.GetString("PleaseSelectBuildersTeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया वर्ग निवडा.
        /// </summary>
        internal static string PleaseSelectCategory {
            get {
                return ResourceManager.GetString("PleaseSelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया कॉन्फिगरेशन निवडा.
        /// </summary>
        internal static string PleaseSelectConfig {
            get {
                return ResourceManager.GetString("PleaseSelectConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया मजला निवडा.
        /// </summary>
        internal static string PleaseSelectFloor {
            get {
                return ResourceManager.GetString("PleaseSelectFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया व्याज स्तर निवडा.
        /// </summary>
        internal static string PleaseSelectInterestLevel {
            get {
                return ResourceManager.GetString("PleaseSelectInterestLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया पार्टी प्रकार निवडा.
        /// </summary>
        internal static string PleaseSelectPartyType {
            get {
                return ResourceManager.GetString("PleaseSelectPartyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया पास महिना आणि वर्ष निवडा.
        /// </summary>
        internal static string PleaseSelectPossessionMonthandYear {
            get {
                return ResourceManager.GetString("PleaseSelectPossessionMonthandYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया प्रकल्प मंजूर महिना आणि वर्ष निवडा.
        /// </summary>
        internal static string PleaseSelectProjectApprovedMonthandYear {
            get {
                return ResourceManager.GetString("PleaseSelectProjectApprovedMonthandYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया मालमत्ता श्रेणी निवडा.
        /// </summary>
        internal static string PleaseSelectPropertyCategory {
            get {
                return ResourceManager.GetString("PleaseSelectPropertyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया मालमत्ता दर्शविणे निवडा.
        /// </summary>
        internal static string PleaseSelectPropertyFacing {
            get {
                return ResourceManager.GetString("PleaseSelectPropertyFacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया मालमत्ता स्थिती निवडा.
        /// </summary>
        internal static string PleaseSelectPropertyStatus {
            get {
                return ResourceManager.GetString("PleaseSelectPropertyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया मालमत्ता प्रकार निवडा.
        /// </summary>
        internal static string PleaseSelectPropertyType {
            get {
                return ResourceManager.GetString("PleaseSelectPropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया मालमत्ता विशाल निवडा.
        /// </summary>
        internal static string PleaseSelectPropertyvastu {
            get {
                return ResourceManager.GetString("PleaseSelectPropertyvastu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया संमेलनाचा हेतू निवडा.
        /// </summary>
        internal static string PleaseSelectPurposeofMeeting {
            get {
                return ResourceManager.GetString("PleaseSelectPurposeofMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया साइट निवडा.
        /// </summary>
        internal static string PleaseSelectSite {
            get {
                return ResourceManager.GetString("PleaseSelectSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया रेरा नोंदणीची राज्य निवडा.
        /// </summary>
        internal static string PleaseSelectStateOfRERARegistering {
            get {
                return ResourceManager.GetString("PleaseSelectStateOfRERARegistering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया स्थिती निवडा.
        /// </summary>
        internal static string PleaseSelectStatus {
            get {
                return ResourceManager.GetString("PleaseSelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया लघुप्रतिमा निवडा.
        /// </summary>
        internal static string PleaseSelectThumbnail {
            get {
                return ResourceManager.GetString("PleaseSelectThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया टॉवर निवडा.
        /// </summary>
        internal static string PleaseSelectTower {
            get {
                return ResourceManager.GetString("PleaseSelectTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया प्रकार निवडा.
        /// </summary>
        internal static string PleaseSelectType {
            get {
                return ResourceManager.GetString("PleaseSelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कृपया वर्ष निवडा.
        /// </summary>
        internal static string PleaseSelectYear {
            get {
                return ResourceManager.GetString("PleaseSelectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ताब्यात.
        /// </summary>
        internal static string Possession {
            get {
                return ResourceManager.GetString("Possession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to किंमत.
        /// </summary>
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दर चौरस फूट किंमत.
        /// </summary>
        internal static string PricePerSqFt {
            get {
                return ResourceManager.GetString("PricePerSqFt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्राधान्य.
        /// </summary>
        internal static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्प.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्प सुविधा.
        /// </summary>
        internal static string ProjectAmenities {
            get {
                return ResourceManager.GetString("ProjectAmenities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्प मंजूर.
        /// </summary>
        internal static string ProjectApprovedOn {
            get {
                return ResourceManager.GetString("ProjectApprovedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्प कोड.
        /// </summary>
        internal static string ProjectCode {
            get {
                return ResourceManager.GetString("ProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्प यादी.
        /// </summary>
        internal static string ProjectList {
            get {
                return ResourceManager.GetString("ProjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्प मास्टर.
        /// </summary>
        internal static string ProjectMaster {
            get {
                return ResourceManager.GetString("ProjectMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्पाचे नाव.
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्प नाव / पक्षाचे नाव.
        /// </summary>
        internal static string ProjectNamePartyName {
            get {
                return ResourceManager.GetString("ProjectNamePartyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रोजेक्ट प्रीफिटिंग.
        /// </summary>
        internal static string ProjectPrefitting {
            get {
                return ResourceManager.GetString("ProjectPrefitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रोजेक्टटाइप.
        /// </summary>
        internal static string ProjectType {
            get {
                return ResourceManager.GetString("ProjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्प प्रकार यादी.
        /// </summary>
        internal static string ProjectTypeList {
            get {
                return ResourceManager.GetString("ProjectTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रोजेक्टटाइप मास्टर.
        /// </summary>
        internal static string ProjectTypeMaster {
            get {
                return ResourceManager.GetString("ProjectTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रोजेक्टटाइप नाव.
        /// </summary>
        internal static string ProjectTypeName {
            get {
                return ResourceManager.GetString("ProjectTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता श्रेणी.
        /// </summary>
        internal static string PropertyCategory {
            get {
                return ResourceManager.GetString("PropertyCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता श्रेणी यादी.
        /// </summary>
        internal static string PropertyCategoryList {
            get {
                return ResourceManager.GetString("PropertyCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता श्रेणी मास्टर.
        /// </summary>
        internal static string PropertyCategoryMaster {
            get {
                return ResourceManager.GetString("PropertyCategoryMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता श्रेणी नाव.
        /// </summary>
        internal static string PropertyCategoryName {
            get {
                return ResourceManager.GetString("PropertyCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता कोड.
        /// </summary>
        internal static string PropertyCode {
            get {
                return ResourceManager.GetString("PropertyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रॉपर्टी कॉन्फिगरेशन.
        /// </summary>
        internal static string PropertyConfig {
            get {
                return ResourceManager.GetString("PropertyConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रॉपर्टी कॉन्फिगरेशन यादी.
        /// </summary>
        internal static string PropertyConfigList {
            get {
                return ResourceManager.GetString("PropertyConfigList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रॉपर्टी कॉन्फिगरेशन मास्टर.
        /// </summary>
        internal static string PropertyConfigMaster {
            get {
                return ResourceManager.GetString("PropertyConfigMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रॉपर्टी कॉन्फिगरेशन नाव.
        /// </summary>
        internal static string PropertyConfigName {
            get {
                return ResourceManager.GetString("PropertyConfigName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता प्रवेश.
        /// </summary>
        internal static string PropertyEntry {
            get {
                return ResourceManager.GetString("PropertyEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्तेचा सामना.
        /// </summary>
        internal static string PropertyFacing {
            get {
                return ResourceManager.GetString("PropertyFacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता दर्शविणारी यादी.
        /// </summary>
        internal static string PropertyFacingList {
            get {
                return ResourceManager.GetString("PropertyFacingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रॉपर्टी फेसिंग मास्टर.
        /// </summary>
        internal static string PropertyFacingMaster {
            get {
                return ResourceManager.GetString("PropertyFacingMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्तेचे नाव.
        /// </summary>
        internal static string PropertyFacingName {
            get {
                return ResourceManager.GetString("PropertyFacingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता मजला.
        /// </summary>
        internal static string PropertyFloor {
            get {
                return ResourceManager.GetString("PropertyFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता मजल्याची यादी.
        /// </summary>
        internal static string PropertyFloorList {
            get {
                return ResourceManager.GetString("PropertyFloorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रॉपर्टी फ्लोर मास्टर.
        /// </summary>
        internal static string PropertyFloorMaster {
            get {
                return ResourceManager.GetString("PropertyFloorMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रॉपर्टी फ्लोरचे नाव.
        /// </summary>
        internal static string PropertyFloorName {
            get {
                return ResourceManager.GetString("PropertyFloorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता व्याज.
        /// </summary>
        internal static string PropertyInterest {
            get {
                return ResourceManager.GetString("PropertyInterest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता व्याज यादी.
        /// </summary>
        internal static string PropertyInterestList {
            get {
                return ResourceManager.GetString("PropertyInterestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता यादी.
        /// </summary>
        internal static string PropertyList {
            get {
                return ResourceManager.GetString("PropertyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता विहंगावलोकन.
        /// </summary>
        internal static string PropertyOverview {
            get {
                return ResourceManager.GetString("PropertyOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रॉपर्टी पार्टी.
        /// </summary>
        internal static string PropertyParty {
            get {
                return ResourceManager.GetString("PropertyParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता स्थिती.
        /// </summary>
        internal static string PropertyStatus {
            get {
                return ResourceManager.GetString("PropertyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता स्थिती यादी.
        /// </summary>
        internal static string PropertyStatusList {
            get {
                return ResourceManager.GetString("PropertyStatusList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता स्थिती मास्टर.
        /// </summary>
        internal static string PropertyStatusMaster {
            get {
                return ResourceManager.GetString("PropertyStatusMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता स्थिती नाव.
        /// </summary>
        internal static string PropertyStatusName {
            get {
                return ResourceManager.GetString("PropertyStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्तेचा प्रकार.
        /// </summary>
        internal static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता प्रकार यादी.
        /// </summary>
        internal static string PropertyTypeList {
            get {
                return ResourceManager.GetString("PropertyTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रॉपर्टी प्रकार मास्टर.
        /// </summary>
        internal static string PropertyTypeMaster {
            get {
                return ResourceManager.GetString("PropertyTypeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्तेचे नाव.
        /// </summary>
        internal static string PropertyTypeName {
            get {
                return ResourceManager.GetString("PropertyTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रॉपर्टी वास्तु.
        /// </summary>
        internal static string PropertyVastu {
            get {
                return ResourceManager.GetString("PropertyVastu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मालमत्ता वास्तू यादी.
        /// </summary>
        internal static string PropertyVastuList {
            get {
                return ResourceManager.GetString("PropertyVastuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रॉपर्टी वास्तु मास्टर.
        /// </summary>
        internal static string PropertyVastuMaster {
            get {
                return ResourceManager.GetString("PropertyVastuMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to हेतू.
        /// </summary>
        internal static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to उद्देश यादी.
        /// </summary>
        internal static string PurposeList {
            get {
                return ResourceManager.GetString("PurposeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to उद्देश मास्टर.
        /// </summary>
        internal static string PurposeMaster {
            get {
                return ResourceManager.GetString("PurposeMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to हेतू नाव.
        /// </summary>
        internal static string PurposeName {
            get {
                return ResourceManager.GetString("PurposeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सभेचा हेतू.
        /// </summary>
        internal static string PurposeofMeeting {
            get {
                return ResourceManager.GetString("PurposeofMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कारण आवश्यक.
        /// </summary>
        internal static string ReasonRequired {
            get {
                return ResourceManager.GetString("ReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पासून नोंदणीकृत.
        /// </summary>
        internal static string RegisteredSince {
            get {
                return ResourceManager.GetString("RegisteredSince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टीका.
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टीका.
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रेरा लागू.
        /// </summary>
        internal static string RERAApplicable {
            get {
                return ResourceManager.GetString("RERAApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रेरा क्र.
        /// </summary>
        internal static string RERANo {
            get {
                return ResourceManager.GetString("RERANo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रेरा अनिवार्य नाही.
        /// </summary>
        internal static string RERANocompulsory {
            get {
                return ResourceManager.GetString("RERANocompulsory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अनुसूचित अभ्यागत.
        /// </summary>
        internal static string ScheduledVisit {
            get {
                return ResourceManager.GetString("ScheduledVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पुढील अभ्यागत वेळापत्रक.
        /// </summary>
        internal static string ScheduleNextVisit {
            get {
                return ResourceManager.GetString("ScheduleNextVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to पुढील अभ्यागत तारीख वेळापत्रक.
        /// </summary>
        internal static string ScheduleNextVisitDate {
            get {
                return ResourceManager.GetString("ScheduleNextVisitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बिल्डर निवडा.
        /// </summary>
        internal static string SelectBuilder {
            get {
                return ResourceManager.GetString("SelectBuilder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to बिल्डरचे कार्यसंघ सदस्य निवडा.
        /// </summary>
        internal static string SelectBuildersTeamMembers {
            get {
                return ResourceManager.GetString("SelectBuildersTeamMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कॉन्फिगरेशन निवडा.
        /// </summary>
        internal static string SelectConfig {
            get {
                return ResourceManager.GetString("SelectConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to निर्यात स्वरूप निवडा.
        /// </summary>
        internal static string SelectExportFormat {
            get {
                return ResourceManager.GetString("SelectExportFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to मजला निवडा.
        /// </summary>
        internal static string SelectFloor {
            get {
                return ResourceManager.GetString("SelectFloor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एकाधिक ब्लॉग प्रतिमा आणि फायली निवडा.
        /// </summary>
        internal static string SelectMultipleBlogImagesandFiles {
            get {
                return ResourceManager.GetString("SelectMultipleBlogImagesandFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to एकाधिक मालमत्ता फोटो आणि माहितीपत्रक निवडा.
        /// </summary>
        internal static string SelectMultiplePropertyPhotosandBrochure {
            get {
                return ResourceManager.GetString("SelectMultiplePropertyPhotosandBrochure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रकल्प निवडा.
        /// </summary>
        internal static string SelectProject {
            get {
                return ResourceManager.GetString("SelectProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थिती निवडा.
        /// </summary>
        internal static string SelectStatus {
            get {
                return ResourceManager.GetString("SelectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लघुप्रतिमा प्रतिमा निवडा.
        /// </summary>
        internal static string SelectThumbnailImage {
            get {
                return ResourceManager.GetString("SelectThumbnailImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टॉवर निवडा.
        /// </summary>
        internal static string SelectTower {
            get {
                return ResourceManager.GetString("SelectTower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वापरकर्ता निवडा.
        /// </summary>
        internal static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लॉगिन ईमेल पाठवा.
        /// </summary>
        internal static string SendLoginEmail {
            get {
                return ResourceManager.GetString("SendLoginEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to साइट पत्ता 1.
        /// </summary>
        internal static string SiteAddressline1 {
            get {
                return ResourceManager.GetString("SiteAddressline1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to साइट पत्ता ओळ 2.
        /// </summary>
        internal static string SiteAddressline2 {
            get {
                return ResourceManager.GetString("SiteAddressline2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to साइट नाव.
        /// </summary>
        internal static string SiteName {
            get {
                return ResourceManager.GetString("SiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to लहान वर्णन.
        /// </summary>
        internal static string SmallDescription {
            get {
                return ResourceManager.GetString("SmallDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to सोशल मीडिया.
        /// </summary>
        internal static string SocialMedia {
            get {
                return ResourceManager.GetString("SocialMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to राज्य.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रेरा राज्य.
        /// </summary>
        internal static string StateOfRERA {
            get {
                return ResourceManager.GetString("StateOfRERA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रेरा यादी राज्य.
        /// </summary>
        internal static string StateOfRERAList {
            get {
                return ResourceManager.GetString("StateOfRERAList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रेरा मास्टर ऑफ स्टेट.
        /// </summary>
        internal static string StateOfRERAMaster {
            get {
                return ResourceManager.GetString("StateOfRERAMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to रेरा नोंदणी राज्य.
        /// </summary>
        internal static string StateOfRERARegistering {
            get {
                return ResourceManager.GetString("StateOfRERARegistering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थिती.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थिती यादी.
        /// </summary>
        internal static string StatusList {
            get {
                return ResourceManager.GetString("StatusList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थिती मास्टर.
        /// </summary>
        internal static string StatusMaster {
            get {
                return ResourceManager.GetString("StatusMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्थिती नाव.
        /// </summary>
        internal static string StatusName {
            get {
                return ResourceManager.GetString("StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टॅग्ज.
        /// </summary>
        internal static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to शीर्षक.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to आजपर्यंत.
        /// </summary>
        internal static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कार्यक्रमाची तारीख.
        /// </summary>
        internal static string ToEventDate {
            get {
                return ResourceManager.GetString("ToEventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टॉवर तपशील.
        /// </summary>
        internal static string TowerDetails {
            get {
                return ResourceManager.GetString("TowerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to टॉवर यादी.
        /// </summary>
        internal static string TowerList {
            get {
                return ResourceManager.GetString("TowerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to युनिट तपशील.
        /// </summary>
        internal static string UnitDetails {
            get {
                return ResourceManager.GetString("UnitDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to युनिट नाव.
        /// </summary>
        internal static string UnitName {
            get {
                return ResourceManager.GetString("UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to युनिट स्थिती.
        /// </summary>
        internal static string UnitStatus {
            get {
                return ResourceManager.GetString("UnitStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to युनिट स्थिती यादी.
        /// </summary>
        internal static string UnitStatusList {
            get {
                return ResourceManager.GetString("UnitStatusList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to युनिट स्थिती मास्टर.
        /// </summary>
        internal static string UnitStatusMaster {
            get {
                return ResourceManager.GetString("UnitStatusMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to युनिट स्थिती नाव.
        /// </summary>
        internal static string UnitStatusName {
            get {
                return ResourceManager.GetString("UnitStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to स्वतःचे प्रोफाइल अधिकार अद्यतनित करा.
        /// </summary>
        internal static string UpdateOwnProfileRights {
            get {
                return ResourceManager.GetString("UpdateOwnProfileRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to फोटो अपलोड करा.
        /// </summary>
        internal static string UploadPhotos {
            get {
                return ResourceManager.GetString("UploadPhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वास्तु.
        /// </summary>
        internal static string Vastu {
            get {
                return ResourceManager.GetString("Vastu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to दृश्यमानता स्थिती.
        /// </summary>
        internal static string VisibilityStatus {
            get {
                return ResourceManager.GetString("VisibilityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अभ्यागत प्रवेश.
        /// </summary>
        internal static string VisitEntry {
            get {
                return ResourceManager.GetString("VisitEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अभ्यागत इतिहास.
        /// </summary>
        internal static string VisitHistory {
            get {
                return ResourceManager.GetString("VisitHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अभ्यागत यादी.
        /// </summary>
        internal static string VisitList {
            get {
                return ResourceManager.GetString("VisitList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अभ्यागत क्र.
        /// </summary>
        internal static string VisitNo {
            get {
                return ResourceManager.GetString("VisitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to वेबसाइट दुवा.
        /// </summary>
        internal static string WebsiteLink {
            get {
                return ResourceManager.GetString("WebsiteLink", resourceCulture);
            }
        }
    }
}
